[build]
  command = "npm install && CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1" 